pipeline {
    agent any
    
    environment {
        APP_NAME = 'employee-directory'
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo '📥 Checking out code from GitHub...'
                checkout scm
            }
        }
        
        stage('Environment Check') {
            steps {
                echo '🔍 Verifying environment...'
                sh '''
                    echo "Docker version: $(docker --version)"
                    echo "Docker Compose version: $(docker compose version)"
                    echo "Working directory: $(pwd)"
                    echo "Git branch: ${GIT_BRANCH}"
                    echo "Git commit: ${GIT_COMMIT}"
                '''
            }
        }
        
        stage('Generate Secure .env') {
            steps {
                echo '🔐 Generating .env file from Jenkins credentials...'
                withCredentials([
                    string(credentialsId: 'mysql-password', variable: 'MYSQL_PASSWORD'),
                    string(credentialsId: 'mysql-db', variable: 'MYSQL_DB'),
                    string(credentialsId: 'mysql-user', variable: 'MYSQL_USER'),
                    string(credentialsId: 'mysql-host', variable: 'MYSQL_HOST'),
                    string(credentialsId: 'flask-secret-key', variable: 'SECRET_KEY')
                ]) {
                    sh '''
                        # Create .env file with all required variables
                        cat > .env << ENVFILE
# Auto-generated by Jenkins CI/CD
# Build: ${BUILD_NUMBER}
# Date: $(date)

# MySQL Configuration
MYSQL_HOST=${MYSQL_HOST}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
MYSQL_DB=${MYSQL_DB}

# Flask Configuration
SECRET_KEY=${SECRET_KEY}
FLASK_ENV=production

# Application
APP_PORT=5000
ENVFILE
                        
                        echo "✅ .env file created successfully"
                        echo "File preview (secrets masked):"
                        cat .env | sed 's/PASSWORD=.*/PASSWORD=***HIDDEN***/g' | sed 's/SECRET_KEY=.*/SECRET_KEY=***HIDDEN***/g'
                    '''
                }
            }
        }
        
        stage('Stop Old Containers') {
            steps {
                echo '🛑 Stopping existing containers...'
                sh '''
                    docker compose down || true
                    echo "✅ Old containers stopped"
                '''
            }
        }
        
        stage('Clean Old Images') {
            steps {
                echo '🧹 Cleaning old Docker images...'
                sh '''
                    docker rmi ${APP_NAME}-app || true
                    docker system prune -f
                    echo "✅ Cleanup completed"
                '''
            }
        }
        
        stage('Build Docker Images') {
            steps {
                echo '🔨 Building Docker images...'
                sh '''
                    docker compose build --no-cache
                    echo "✅ Build completed"
                '''
            }
        }
        
        stage('Deploy Application') {
            steps {
                echo '🚀 Deploying application...'
                sh '''
                    docker compose up -d
                    echo "✅ Containers started"
                    echo "⏳ Waiting for services to initialize..."
                    sleep 15
                '''
            }
        }
        
        stage('Verify Deployment') {
            steps {
                echo '✅ Verifying deployment...'
                sh '''
                    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                    echo "Container Status:"
                    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                    docker compose ps
                    
                    echo ""
                    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                    echo "Health Checks:"
                    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                    
                    # Check MySQL health
                    echo "Checking MySQL health..."
                    for i in {1..30}; do
                        MYSQL_HEALTH=$(docker inspect hr_mysql --format='{{.State.Health.Status}}' 2>/dev/null || echo "starting")
                        echo "  [Attempt $i/30] MySQL: $MYSQL_HEALTH"
                        if [ "$MYSQL_HEALTH" = "healthy" ]; then
                            echo "✅ MySQL is healthy!"
                            break
                        fi
                        sleep 2
                    done
                    
                    if [ "$MYSQL_HEALTH" != "healthy" ]; then
                        echo "❌ MySQL health check failed"
                        docker compose logs mysql
                        exit 1
                    fi
                    
                    echo ""
                    # Check Flask application
                    echo "Checking Flask application health..."
                    MAX_ATTEMPTS=30
                    for i in $(seq 1 $MAX_ATTEMPTS); do
                        if curl -f -s http://localhost:5000/health > /dev/null 2>&1; then
                            echo "✅ Flask application is healthy!"
                            echo ""
                            echo "Health endpoint response:"
                            curl -s http://localhost:5000/health | python3 -m json.tool
                            echo ""
                            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                            echo "✅ DEPLOYMENT SUCCESSFUL!"
                            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                            exit 0
                        fi
                        echo "  [Attempt $i/$MAX_ATTEMPTS] Waiting for Flask app..."
                        sleep 2
                    done
                    
                    echo "❌ Flask application health check failed"
                    echo ""
                    echo "Application logs:"
                    docker compose logs app --tail=50
                    exit 1
                '''
            }
        }
    }
    
    post {
        success {
            echo '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
            echo '✅ PIPELINE COMPLETED SUCCESSFULLY!'
            echo '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
            sh '''
                echo ""
                echo "📊 Final Container Status:"
                docker ps --filter "name=hr_" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
                
                echo ""
                echo "🌐 Application Access:"
                echo "   • Main App:     http://$(hostname -I | awk '{print $1}'):5000"
                echo "   • Health Check: http://$(hostname -I | awk '{print $1}'):5000/health"
                
                echo ""
                echo "📊 Resource Usage:"
                docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}" hr_mysql hr_app
            '''
        }
        
        failure {
            echo '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
            echo '❌ PIPELINE FAILED!'
            echo '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
            sh '''
                echo ""
                echo "📊 Container Status:"
                docker ps -a --filter "name=hr_"
                
                echo ""
                echo "📋 Application Logs (last 50 lines):"
                docker compose logs app --tail=50 || true
                
                echo ""
                echo "📋 MySQL Logs (last 50 lines):"
                docker compose logs mysql --tail=50 || true
                
                echo ""
                echo "🔍 Troubleshooting Tips:"
                echo "  1. Check if .env file was created correctly"
                echo "  2. Verify MySQL password matches in both services"
                echo "  3. Check if ports 5000 and 3306 are not already in use"
                echo "  4. Review full logs: docker compose logs"
            '''
        }
        
        always {
            echo '🧹 Cleaning up sensitive files...'
            sh '''
                # Remove .env file (contains secrets)
                if [ -f .env ]; then
                    rm -f .env
                    echo "✅ .env file removed"
                else
                    echo "ℹ️  No .env file to remove"
                fi
                
                # Verify it's gone
                if [ -f .env ]; then
                    echo "⚠️  WARNING: .env file still exists!"
                else
                    echo "✅ Workspace is clean (no .env file)"
                fi
            '''
        }
    }
}
